[[constraint]]
  name = "github.com/gruntwork-io/terratest"
  version = "0.17.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.7"